Gino-Hsu/simple-twitter

.gitattributes
=> feat: add file .gitattributes

.env, .github/workflows/.deploy.yml, package.json
1. Set deploy
2. npm i axios
3. npm i gh-pages
4. npm i sweetalert2
=> feat: set deploy

src/App.scss, src/index.scss
**環境建置**
1.增加font-family
2.reset css
請查收，辛苦了
祝好
=> feat: add font-family

src/App.jsx, src/UIComponents/ButtonUI.module.scss, src/UIComponents/PopularUserItem.jsx, src/UIComponents/PopularUserItem.module.scss, src/components/popularUser/PopularUser.jsx, src/components/popularUser/PopularUser.module.scss
1.添加PopularUser component並完成RWD
2.修改共用元件 Button 的 css
3.修改引用var.scss 名稱 （var --> color）
4.修改PopularUserItem 文字輸入太長會破版的問題
再麻煩了！辛苦了
祝好！
=> feat: add component : PopularUser

src/App.jsx, src/components/replyModal/ReplyModal.jsx, src/components/replyModal/ReplyModal.module.scss
**Reply Modal**
- 內需要加入他人推文 component
感謝~
=> Component c08

src/App.jsx, src/UIComponents/ReplyListItem.jsx, src/UIComponents/ReplyListItem.module.scss, src/UIComponents/UserCardItem.jsx, src/components/SideBar/SideBar.module.scss, src/components/replyModal/ReplyModal.jsx, src/pages/Home.jsx, src/pages/Home.module.scss
**ReplyListItem UI 元件**
- 完成 ReplyListItem UI 元件
- 此元件於 Reply 中共用
*暫時使用 dummy data，未來須透過串接 API 引用資料
=> feat: add replylist item component

src/App.jsx, src/App.scss, src/UIComponents/ReplyListItem.module.scss
**修復錯誤**
- 修復 goole-font 沒作用的 bug
- 解決：在 App.scss 刪除 font: inherit 的設定
麻煩了~👍
=> debug：修復 font-family 載入失敗

src/App.jsx, src/UIComponents/layout/NavItem.module.scss, src/UIComponents/listItems/TweetListItem.jsx, src/UIComponents/listItems/TweetListItem.module.scss, src/components/SideBar/SideBar.jsx, src/components/SideBar/SideBar.module.scss, src/components/mainTweet/MainTweet.jsx, src/components/mainTweet/MainTweet.module.scss, src/components/mainTweet/tweetInput/TweetInput.jsx, src/components/mainTweet/tweetInput/TweetInput.module.scss, src/components/popularUser/PopularUser.module.scss, src/pages/Home.jsx, src/pages/Home.module.scss
**重構**
重構MainTweet, SideBar, PopularUser 3個component
針對Home頁面做程式碼的優化，更改tweetInput版面的寫法。
針對MainTweet 爆板問題優化。
PopularUser 設計稿因為是7組使用者，但User story 要求10組，調整版面以符合User story 。
辛苦了！！！
=> refactor:MainTweet, SideBar, PopularUser

src/App.jsx, src/UIComponents/buttons/ButtonUI.module.scss, src/UIComponents/listItems/ReplyListItem.module.scss, src/UIComponents/listItems/TweetListItem.module.scss, src/components/relyList/RelyList.jsx, src/components/relyList/ReplyList.module.scss, src/pages/Home.jsx, src/pages/Reply.jsx
**新增 Reply page 元件**
- 完成 Reply page
- 符合 RWD
*各項資料使用 dummy data，未來須更新為 API 資料
=> feat: add reply page

src/App.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/UIComponents/listItems/TweetListItem.module.scss, src/components/SideBar/SideBar.jsx, src/components/popularUser/PopularUser.module.scss, src/pages/Home.jsx, src/pages/Home.module.scss, src/pages/layout/Layout.jsx, src/pages/layout/Layout.module.scss
1.重構畫面: 修改原本使用。的地方，改用css寫一個實心的圖案
2.增加底色
3.新增Layout 資料夾及檔案
4.測試路由，修改Home頁面
辛苦了！
祝好
=> Refactor 01

src/App.jsx, src/pages/Home.jsx
##環境設定##
完成路由的設定，未使用到的先註解，後續完成相對應畫面的人，在測試該路由是否可以使用！
辛苦了！
祝好！
=> feat: Complete routing settings

src/components/popularUser/PopularUser.module.scss
**重購 popularUser SCSS**
- 重購 popularUser SCSS：.popularUser__container 增加 max-height:100%
- 使當超過 100vh 時 scroll bar 可以正常被顯示
辛苦了~
=> Refactor popular user

src/components/SideBar/SideBar.jsx, src/components/SideBar/SideBar.module.scss, src/components/currentUser/CurrentUser.module.scss, src/components/popularUser/PopularUser.module.scss, src/index.scss
**增加 scroll bar 樣式**
- 增加 scroll bar 樣式
=> feat: add scrollBar style

src/App.jsx, src/UIComponents/admin/AdminListItem.jsx, src/UIComponents/admin/AdminListItem.module.scss, src/UIComponents/layout/AdminNavItem.jsx, src/UIComponents/layout/AdminNavItem.module.scss, src/components/SideBar/AdminSideBar.jsx, src/components/SideBar/AdminSideBar.module.scss, src/components/currentUser/MobileUser.module.scss, src/pages/AdminTweets.jsx, src/pages/AdminTweets.module.scss, src/pages/layout/Layout.module.scss
=> feat: AdminTweets complete

src/App.jsx
**整理App.jsx檔案**
確認路由時否都有正確、重新排版
=> config: rotuer

src/API/authorization.js, src/App.jsx, src/UIComponents/buttons/ButtonUI.jsx, src/UIComponents/buttons/ButtonUI.module.scss, src/UIComponents/headers/SettingHeader.jsx, src/UIComponents/inputs/Input.module.scss, src/components/SideBar/SideBar.module.scss, src/components/loginForm/LoginForm.jsx, src/index.scss, src/pages/Login.jsx, src/pages/Setting.module.scss, src/utils/helpers.js
**新增樣式**
-add button & input style
=> Style button

src/App.jsx, src/UIComponents/admin/AdminUserCard.module.scss, src/UIComponents/buttons/ButtonUI.module.scss, src/UIComponents/inputs/Input.module.scss, src/components/EditModal/EditModal.jsx, src/components/EditModal/EditModal.module.scss, src/components/SideBar/AdminSideBar.module.scss, src/components/SideBar/SideBar.module.scss
**修復 bug**
-修復 app & input's bug
=> fix: fix app & input's style

src/API/authorization.js, src/App.scss, src/UIComponents/inputs/Input.jsx, src/UIComponents/inputs/Input.module.scss, src/components/adminLoginForm/AdminLoginForm.jsx, src/components/loginForm/LoginForm.jsx, src/components/loginForm/LoginForm.module.scss, src/components/registForm/RegistForm.jsx, src/pages/Login.jsx, src/utils/helpers.js
**增加 Login API**
- 完成 Login api 串接，取得 token 後存進 localStorage
- 表單驗證，帳號或密碼不能為空值
- 當使用者帳號或密碼任一輸入空值，並提送表單時，顯示錯誤訊息並停止 api 請求
- 加入 swal2 提示訊息
感謝~
=> Api auth v2

src/API/authorization.js, src/UIComponents/inputs/Input.jsx, src/components/registForm/RegistForm.jsx, src/components/registForm/RegistForm.module.scss, src/pages/Login.jsx, src/pages/Regist.jsx
**串接註冊頁 api**
- 完成使用者註冊 api 串接
- 完成表單驗證
*後端驗證尚未完成，等候端完成 error message
=> feat: add regist api

src/UIComponents/inputs/Input.jsx, src/components/adminLoginForm/AdminLoginForm.jsx, src/components/loginForm/LoginForm.jsx
=> fix: ESLint error

src/UIComponents/listItems/TweetListItem.jsx
=> fix: fix TweetListItem's link

src/App.jsx, src/UIComponents/layout/NavItem.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/UIComponents/modals/BackDrop.jsx, src/UIComponents/modals/BackDrop.module.scss, src/UIComponents/modals/Modal.jsx, src/components/EditModal/EditModal.jsx, src/components/EditModal/EditModal.module.scss, src/components/SideBar/SideBar.jsx, src/components/currentUser/CurrentUser.jsx, src/components/mainTweet/MainTweet.jsx, src/components/relyList/RelyList.jsx, src/components/replyModal/ReplyModal.jsx, src/components/replyModal/ReplyModal.module.scss, src/components/tweetModal/TweetModal.jsx, src/pages/CurrentUserLike.jsx, src/pages/CurrentUserReply.jsx, src/pages/CurrentUserTweet.jsx, src/pages/Home.jsx, src/pages/OtherUserLike.jsx, src/pages/OtherUserTweet.jsx, src/pages/Reply.jsx, src/pages/layout/Layout.jsx
**功能**
1.完成所有推文按鈕可以使用彈跳出視窗
2.完成self-user 要可以回復推文的圖案可以使用彈跳視窗（其他有做但無法測試）
3.完成修改個人資料按鈕的彈跳視窗
辛苦了！
=> Function setting

src/API/tweetApi.js, src/App.jsx, src/UIComponents/admin/AdminListItem.jsx, src/UIComponents/admin/AdminListItem.module.scss, src/components/tweetModal/TweetModal.jsx, src/pages/AdminTweets.jsx, src/pages/Home.jsx, src/utils/helpers.js
**串接推文&刪除推文api**
- 完成推文 api 串接
- 完成管理員刪除推文 api 串接
麻煩過目了~
=> feat: add post tweet api

src/App.jsx, src/UIComponents/modals/Modal.module.scss, src/components/currentUser/CurrentUser.jsx, src/components/mainTweet/MainTweet.jsx, src/components/tweetModal/TweetModal.jsx, src/components/tweetModal/TweetModal.module.scss
**修正 TweetModal**
- 修正 TweetModal 跑版，畫面 < 800px 時無法置頂，button 邊距不夠 margin: 17px 0
- 修正 TweetModal 使用者頭貼為 Dummy Data
=> fix: fix tweetModal's style & current user's avatar

src/App.jsx, src/UIComponents/layout/NavItem.jsx, src/components/SideBar/SideBar.jsx, src/components/currentUser/CurrentUser.jsx, src/components/mainTweet/MainTweet.jsx, src/components/tweetModal/TweetModal.jsx, src/pages/Home.jsx, src/pages/layout/Layout.jsx, src/utils/helpers.js
=> Function mode v2

src/App.jsx, src/components/mainTweet/tweetInput/TweetInput.jsx, src/components/tweetModal/TweetModal.jsx, src/pages/Reply.jsx, src/utils/helpers.js
=> fix: fix effect2

src/App.jsx, src/UIComponents/layout/NavItem.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/components/SideBar/SideBar.jsx, src/components/currentUser/CurrentUser.jsx, src/components/mainTweet/MainTweet.jsx, src/components/relyList/RelyList.jsx, src/components/tweetModal/TweetModal.jsx, src/contexts/modalControlContext/ModalControlContext.jsx, src/pages/CurrentUserLike.jsx, src/pages/CurrentUserReply.jsx, src/pages/CurrentUserTweet.jsx, src/pages/Home.jsx, src/pages/OtherUserLike.jsx, src/pages/OtherUserTweet.jsx, src/pages/Reply.jsx, src/pages/Setting.jsx, src/pages/layout/Layout.jsx
=> refactor: modalContext OK

src/App.jsx, src/UIComponents/layout/NavItem.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/UIComponents/tabs/FollowTab.jsx, src/components/SideBar/SideBar.jsx, src/components/currentUser/CurrentUser.jsx, src/components/follow/Follower.jsx, src/components/follow/Following.jsx, src/components/mainTweet/MainTweet.jsx, src/components/relyList/RelyList.jsx, src/components/tweetModal/TweetModal.jsx, src/contexts/modalControlContext/ModalControlContext.jsx, src/contexts/sideBarControlContext/SideBarControlContext.jsx, src/pages/CurrentUserLike.jsx, src/pages/CurrentUserReply.jsx, src/pages/CurrentUserTweet.jsx, src/pages/Home.jsx, src/pages/OtherUserLike.jsx, src/pages/OtherUserTweet.jsx, src/pages/Reply.jsx, src/pages/Setting.jsx, src/pages/layout/Layout.jsx
**重構**
完成：把SideBar變色功能裡的資料傳遞改成context
辛苦了
祝好
=> Refactor side bar context

src/API/ReplyApi.js, src/API/tweetApi.js, src/API/userApi.js, src/App.jsx, src/UIComponents/layout/NavItem.jsx, src/UIComponents/listItems/ReplyListItem.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/UIComponents/listItems/TweetListItem.module.scss, src/components/currentUser/CurrentUser.jsx, src/components/mainTweet/MainTweet.jsx, src/components/otherUser/OtherUser.jsx, src/components/relyList/RelyList.jsx, src/components/relyList/ReplyList.module.scss, src/components/tweetModal/TweetModal.jsx, src/pages/CurrentUserReply.jsx, src/pages/CurrentUserTweet.jsx, src/pages/OtherUserTweet.jsx, src/pages/Reply.jsx, src/utils/helpers.js, src/utils/routeLink.js
=> Api user reply

src/App.jsx, src/pages/CurrentUserTweet.jsx, src/pages/layout/Layout.jsx
=> feat: route

src/API/ReplyApi.js, src/App.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/components/replyModal/ReplyModal.jsx, src/contexts/modalControlContext/ModalControlContext.jsx, src/pages/CurrentUserReply.jsx, src/pages/OtherUserReply.jsx, src/utils/helpers.js
**完成回復 api 串接**
- 使用者點擊回復 icon 可進行回復
- 按下 "回復" 提交表單
=> Api post reply

src/API/ReplyApi.js, src/API/userApi.js, src/App.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/components/replyModal/ReplyModal.jsx, src/contexts/modalControlContext/ModalControlContext.jsx, src/pages/CurrentUserReply.jsx, src/pages/OtherUserReply.jsx, src/utils/helpers.js
修正 Get currentUser api 的 URL
"/users" -> "/current_user"
=> Debug current user api

src/API/likeApi.js, src/App.jsx, src/UIComponents/listItems/TweetListItem.jsx, src/UIComponents/tabs/FollowTab.jsx, src/components/currentUser/MobileUser.jsx, src/components/follow/Follower.jsx, src/components/follow/Following.jsx, src/pages/AdminUsers.module.scss, src/pages/CurrentUserLike.jsx, src/pages/Home.jsx, src/pages/OtherUserLike.jsx, src/pages/OtherUserReply.jsx, src/utils/helpers.js
**修改**
1.修改 likeApi錯誤
2.更改OtherUserLike & UserLike與資料庫連接問題
3.修改後台使用者圖片呈現方式
！！！ replyApi的檔案名稱還是都會變大寫
辛苦了
祝好
=> fix: likeApi bug

src/components/relyList/RelyList.jsx, src/pages/Reply.jsx
=> fix: debug

src/UIComponents/admin/AdminUserCard.module.scss, src/UIComponents/layout/PopularUserItem.jsx, src/UIComponents/listItems/FollowListItem.jsx, src/components/SideBar/SideBar.jsx, src/components/currentUser/CurrentUser.jsx, src/components/otherUser/OtherUser.jsx, src/components/settingForm/SettinForm.jsx, src/pages/Follower.jsx, src/pages/Following.jsx, src/pages/OtherUserLike.jsx, src/pages/OtherUserReply.jsx, src/pages/OtherUserTweet.jsx
**功能**
1.在following 跟 follower 可以點擊跟隨按鈕
2.在其他使用者的頁面可以點擊跟隨按鈕
3.修改following 跟 follower 放反的地方
4.新增手機版登出功能
=> Fix link v2

src/components/EditModal/EditModal.jsx, src/components/relyList/RelyList.jsx, src/components/relyList/ReplyList.module.scss, src/components/replyModal/ReplyModal.jsx, src/components/tweetModal/TweetModal.jsx, src/contexts/modalControlContext/ModalControlContext.jsx, src/pages/Reply.jsx
**功能**
1.修復reply頁面無法點擊回覆以及愛心
2.修復reply頁面無法連結發文者
3.修復reply頁面無法自動更新
4.新增彈跳視窗發送成功自動消失
辛苦了
祝好
=> Fix reply icon

src/UIComponents/headers/BtnHeader.jsx, src/UIComponents/headers/TextHeader.jsx, src/UIComponents/headers/UserHeader.jsx, src/components/popularUser/PopularUser.jsx, src/components/relyList/RelyList.jsx, src/components/settingForm/SettinForm.jsx, src/pages/CurrentUserTweet.jsx, src/pages/Follower.jsx, src/pages/Following.jsx, src/pages/Home.jsx, src/pages/OtherUserLike.jsx, src/pages/OtherUserReply.jsx, src/pages/OtherUserTweet.jsx
**功能**
1.修復follower 跟 following 點擊按鈕未能及時更新bug
2.修復其他使用者的頁面點擊 跟隨/取消跟隨 無法即時更新Bug
3.新增點擊圖示(<--)可以回到上一頁功能
辛苦了
祝好
=> Fix follow v3

README.md
**修改**
修改排版
clone 下來有兩個問題：
1. replyApi.js 這個檔案會變成 ReplyApi.js
2. editModal 這個資料夾名稱會變成 EditModal 
辛苦了 祝好
=> fix: Typesetting

src/components/EditModal/EditModal.jsx
=> fix: debug-editModal

src/contexts/usersContext/OtherUserContext.jsx
=> fix:tidying code

src/components/currentUser/CurrentUser.module.scss, src/components/currentUser/MobileUser.module.scss, src/components/otherUser/OtherUser.module.scss
=> fix: name & account style

src/components/relyList/RelyList.jsx
=> fix: back page

src/App.jsx, src/UIComponents/buttons/ButtonUI.jsx, src/UIComponents/modals/Modal.module.scss, src/components/editModal/EditModal.jsx, src/components/replyModal/ReplyModal.jsx, src/components/tweetModal/TweetModal.jsx, src/contexts/buttonControlContext/ButtonControlContext.jsx, src/pages/Login.jsx, src/pages/Regist.jsx
=> Fun btn disable
